### PR TITLE
Create Ansh_Kothari.cpp

### PR DESCRIPTION
**Pull request by anshgeez31**
Issue: 195

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Himanshu276330** [comment]
@anshgeez31 nice work bro.
But your code is not so optimal.
If T=100 and in each test case, if given n=1e5 then every time a vector of 1e5 is created, overall time and space complexity are 1e7. 
which is not so good.
It may be better that you create a vector array before taking test cases.
That makes your code so efficient.
Time complexity == 1e5.
Space complexity == 1e5.

Please make these changes and create a PR.
Sorry for the late reviews.

**Comment by anshgeez31** [comment]
@Himanshu276330 Have a look now.

**Comment by Himanshu276330** [comment]
Ya, it looks better.

**Comment by Himanshu276330** [comment]
Great work! @anshgeez31 

Congratulations as your PR is going to be accepted. Best of luck with your journey.

**Pull request merged**
