### PR TITLE
Create iit2022004.c

### PR DESCRIPTION
**Pull request by VatsalBhuva11**
Issue: 84

Short description of what this resolves:
Implemented Binary Search, in C

Changes proposed in this pull request and/or Screenshots of changes:
Screenshot 2022-12-21 143458

### CODE REVIEW

**Comment by Himanshu276330** [comment]
Great work! @VatsalBhuva11 

Congratulations as your PR is going to be accepted. Best of luck with your journey.

**Comment by pankaj1707k** [comment]
Points updated!

**Comment by Himanshu276330** [comment]
If the point is not updated, then contact @hdelic#6900 on discord.

**Comment by VatsalBhuva11** [comment]
> If the point is not updated, then contact @hdelic#6900 on discord.

where do i check my current points?

**Comment by VatsalBhuva11** [comment]
@Himanshu276330 
> If the point is not updated, then contact @hdelic#6900 on discord.

where do i check my current points?

**Pull request merged**
