### PR TITLE
Updated coderData json file

### PR DESCRIPTION
**Pull request by anshgeez31**
Issue: 1

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Himanshu276330** [comment]
@anshgeez31 
Resolve the merge conflict.

**Comment by anshgeez31** [comment]
@Himanshu276330  Have merged conflicts. Do check it.

**Comment by Himanshu276330** [comment]
There is still a conflict.

**Comment by Himanshu276330** [comment]
Firstly, pull the previous change then add your data below not between the file.

**Comment by Himanshu276330** [comment]
Great work! @anshgeez31 

Congratulations as your PR is going to be accepted. Best of luck with your journey.

**Pull request merged**
